### ISSUE TITLE
语法问题

### ISSUE THREAD

**Issue by smelike** [myrual/mixin_client_demo#2]
E:\python\mixin_client_demo>python home_cnb.py
  File "home_cnb.py", line 55
    print(mixindata)
                   ^
TabError: inconsistent use of tabs and spaces in indentation

#我是用的是 python3.6 语法不至于会这样

**Comment by myrual** [comment]
这个代码是基于python2.6写的。如果用python3，可以看 https://github.com/awesome-mixin-network/mixin_network_sdk_resource
